from pathlib import Path

p = Path('frontend/src/pages/ProfilePage.jsx')
text = p.read_text(encoding='utf-8')
old1 = "  const [profile, setProfile] = useState(null);\n  const [editing, setEditing] = useState(false);\n  const navigate = useNavigate();\n  const [form, setForm] = useState(initialForm);\n  const [avatarUploading, setAvatarUploading] = useState(false);\n  const avatarInputRef = useRef(null);\n  const [periods, setPeriods] = useState([]);\n"
new1 = "  const [profile, setProfile] = useState(null);\n  const [editing, setEditing] = useState(false);\n  const navigate = useNavigate();\n  const [form, setForm] = useState(initialForm);\n  const [avatarUploading, setAvatarUploading] = useState(false);\n  const [avatarLoadError, setAvatarLoadError] = useState(false);\n  const avatarInputRef = useRef(null);\n  const [periods, setPeriods] = useState([]);\n"
old2 = "    try {\n      const formData = new FormData();\n      formData.append('file', file);\n      const res = await uploadProfileImage(formData);\n      console.log('uploadProfileImage response', res);\n      if (res?.success) {\n"
new2 = "    try {\n      setAvatarLoadError(false);\n      const formData = new FormData();\n      formData.append('file', file);\n      const res = await uploadProfileImage(formData);\n      console.log('uploadProfileImage response', res);\n      if (res?.success) {\n"
old3 = "        const normalizedProfile = {\n          ...(profile || {}),\n          ...(next || {}),\n          profileImageUrl: next?.profileImageUrl || profile?.profileImageUrl || '',\n          avatar: next?.profileImageUrl || next?.avatar || profile?.profileImageUrl || profile?.avatar || '',\n          periodName: next?.periodName || profile?.periodName || '',\n"
new3 = "        const normalizedProfile = {\n          ...(profile || {}),\n          ...(next || {}),\n          profileImageUrl: next?.profileImageUrl || next?.avatar || profile?.profileImageUrl || profile?.avatar || '',\n          avatar: next?.profileImageUrl || next?.avatar || profile?.profileImageUrl || profile?.avatar || '',\n          periodName: next?.periodName || profile?.periodName || '',\n"
old4 = "            <div class=\"profile-avatar-wrapper\">\n              <div class=\"avatar profile-avatar\" onClick={handleAvatarClick} style={{ cursor: 'pointer' }}>\n                {profile?.profileImageUrl ? (\n                  // eslint-disable-next-line jsx-a11y/img-redundant-alt\n                  <img src={profile.profileImageUrl} alt=\"avatar\" style={{ width: '100%', height: '100%', borderRadius: '12px', objectFit: 'cover' }} />\n                ) : (\n                  displayInitials\n                )}\n              </div>\n            </div>\n"
new4 = "            <div class=\"profile-avatar-wrapper\">\n              <div class=\"avatar profile-avatar\" onClick={handleAvatarClick} style={{ cursor: 'pointer' }}>\n                {profile?.profileImageUrl && !avatarLoadError ? (\n                  // eslint-disable-next-line jsx-a11y/img-redundant-alt\n                  <img\n                    src={profile.profileImageUrl}\n                    alt=\"avatar\"\n                    style={{ width: '100%', height: '100%', borderRadius: '12px', objectFit: 'cover' }}\n                    onError={() => {\n                      console.warn('Avatar image failed to load:', profile.profileImageUrl);\n                      setAvatarLoadError(true);\n                    }}\n                  />\n                ) : (\n                  displayInitials\n                )}\n              </div>\n            </div>\n"
for old, new in [(old1, new1), (old2, new2), (old3, new3), (old4, new4)]:
    if old not in text:
        raise SystemExit('pattern not found')
    text = text.replace(old, new, 1)
p.write_text(text, encoding='utf-8')
print('patched')
